name: Build and Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-and-release:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        working-directory: ./webapp
        run: npm install --legacy-peer-deps
        
      - name: Build Web App
        working-directory: ./webapp
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './webapp/dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      - name: Package Extension
        run: zip -r deutschway-extension.zip extension/
        
      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deutschway-extension
          path: deutschway-extension.zip
          
      - name: Publish Extension Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "deutschway-extension.zip"
          tag: "latest"
          name: "Deutschway Extension (Latest)"
          body: "Download the `deutschway-extension.zip` file, extract it, and load it unpacked in your browser (e.g., chrome://extensions)."
          allowUpdates: true
          makeLatest: true
